spring:
  datasource:
      trade:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        name: trade
        url: jdbc:mysql://scheduler.mysql.rds.aliyuncs.com/trade?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: JH_Trade
        password: Jh_trade18038
      scheduler:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        name: scheduler
        url: jdbc:mysql://scheduler.mysql.rds.aliyuncs.com/scheduler?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: scheduler
        password: jinhui

      #druid配置 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
      druid:
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
             enabled: true
             url-pattern: /druid/*
             login-username: admin
             login-password: admin
        filter:
             stat:
                 log-slow-sql: true
                 slow-sql-millis: 1000
                 merge-sql: true

    #redis配置
  redis:
      open: false  # 是否开启redis缓存  true开启   false关闭
      database: 0  #数据库索引（默认为0）
#      host: 106.14.237.11
#      port: 6379
      password: ogIu590laJnWfPE3      # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
      sentinel:
          master: mymaster  # 哨兵的配置列表
          nodes: 106.14.237.27:16277,106.14.237.27:26377,106.14.237.11:26379

trading-rsa-private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJF52mSHj61LOK56tQrs5xms7yKknRwHHVj9Wlt3ZO6n6fkLvpmNzG+tsw7lpAH848aVHx+S9nMrEtidMfUjkmRNE231LCH5dC9oEznSFM7n5zD9SltApkorl38eWDMrQG1QkfomQoyiYDFn7E6AJ8SYA8oEIDPGBRQ1jOkGXQxdAgMBAAECgYBg50Fhq6c6MRwdpWFJWMsMIFTex7ZbwCV9bK4utVZHXxSMr5UT5g+i6JqYtsFMDa+QTS8BMjz2NGAGaJepijttj+y3Rc2t4yFEERCwIyOiCHNthEvdJkRKHHP9BChaQrYKVtBSLQ+SdWYR+xTw+bSMlrJiRcdJgFAtbsLK3t5wJQJBANfvCoM06ULzjkpfA6CJXyjEQeYvo3mnUmm2nnPvj+9jZGQ4YerLGOj4QsA97WZOtOft1zChWzCFwg/gKila+WMCQQCseAihNSqfWA9XvjV6p49dnlzu+UKd0LQFm+IK+kQKX72p1zR/jQ715EeSiRO4NN5u7F8u5Zuj3E315GwNNa8/AkEAmd2YhRPv3yhDzRTVNdCNQTRPrOFnQGmNHQzm7b/XtYICaDOQ+kiMUH2OuwOlpVASMm3U968SlonJVZyrDlrn9wJAEHoDMQt4P/LUvGgyib46RxJbBIWRpKwMlsCWrr/MAkW1Q+WIYWsjc8BUSh6IYL/EREqWqU9MODJSzFv/Kp/nVwJAeuHRgHyTGyI48UMFQCFG6Dmums4KOaXcau04emUmdZkUyI7rdiZ+Om//EXTZm2RQsRcstZdNQjRc0CdHXpYJNg==
trading-rsa-public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCRedpkh4+tSziuerUK7OcZrO8ipJ0cBx1Y/Vpbd2Tup+n5C76ZjcxvrbMO5aQB/OPGlR8fkvZzKxLYnTH1I5JkTRNt9Swh+XQvaBM50hTO5+cw/UpbQKZKK5d/HlgzK0BtUJH6JkKMomAxZ+xOgCfEmAPKBCAzxgUUNYzpBl0MXQIDAQAB
md5salt: 12345678

#证联后台请求地址
ZLRT_API_BACK_URI: http://219.143.244.227:7082/zlrt-fund
#商户号
INSTU_ID: B00000603
#私钥密码
keyPwd: 111111
#渠道文件生成目录
OUT_FILE_DIRECTORY: /ftp/prod/scheduler/